#!/bin/bash

if [ "$#" -lt 2 ]
then
	printf "usage: $0 run [docker args]\n"
	exit 1
fi

if [ $1 != "run" ]
then
	printf "first argument must be run\n"
	exit 1
fi

shift

if [ ! -f qemu-ppc64le-static ]
then
	printf "qemu-ppc64le-static should be in the current folder\n"
fi

VOLUMES="${VOLUMES} -v qemu-ppc64le-static:/usr/bin/qemu-ppc64le-static"
printf "docker run ${VOLUMES} $* \n"
exec docker run ${VOLUMES} $*
